name: faith_map
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  location: ^8.0.1
  phosphor_flutter: ^2.0.0
  flutter_native_splash: ^2.3.1
  rename: ^2.1.1
  http: ^1.0.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  animations: ^2.0.7
  url_launcher: ^6.1.0 
  carousel_slider: ^5.0.0
  flutter_map_marker_cluster: ^1.0.0
  shared_preferences: ^2.2.2
  geolocator: ^12.0.0
  lottie: ^3.1.2
  rename_app: 1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


# Standard Flutter config
flutter:
  uses-material-design: true
  assets:
    - assets/images/Splash_logo.png
    - assets/images/iec (2).jpg
    - assets/images/iec (1).jpg
    - assets/images/Asko MKC.jpg
    - assets/images/Slide_1.png 
    - assets/images/Slide_2.png 
    - assets/images/Slide_3.png 
    - assets/images/Kotebe1.png 
    - assets/images/Kotebe2.png
    - assets/images/Sebeta1.jpg
    - assets/images/Sebeta2.jpg
    - assets/images/Sebeta3.jpg
    - assets/images/Jemo1.jpg
    - assets/images/Jemo2.jpg  
    - assets/data/churches.json